import time
from vertexai.generative_models import GenerativeModel

class ModelAsker:
    def __init__(self):
        self.system_prompt = (
            "Instruction: You will receive an image description and a question. Your task is to use the provided image description to answer the question. Do not provide any other text."
        )
        self.model = GenerativeModel(
            model_name="gemini-1.5-flash-002",
            # model_name="gemini-2.0-flash-exp",
            system_instruction=self.system_prompt
        )
        
    def answer_question(self, image_description: str, question: str):
        try:
            prompt_parts = [
                f"Image description: {image_description}",
                f"Question: {question}"
            ]
            response = self.model.generate_content(prompt_parts)
            return response.text.strip()
        except Exception as e:
            raise RuntimeError(str(e))
        
    def process_batch(self, batch_data: list):
        """
        Processes a batch of questions

        Args:
            batch_data (list of dict): A list where each dictionary contains:
                - "path" (str): The path to the image file.
                - "description" (str): The image description generated by the VLM.
                - "question" (str): The question being asked.

        Returns:
            list of tuples: A list of tuples containing (image, answer) pairs.
        """
        results = []
        for data in batch_data:
            result = self.answer_question(data["description"], data["question"])
            results.append((data["path"], result))
            time.sleep(0.25)
        return results